# Nexys4 Pin Assignments
############################
# On-board Slide Switches  #
############################

set_property PACKAGE_PIN U9 [get_ports SW[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[0]]
set_property PACKAGE_PIN U8 [get_ports SW[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[1]]
set_property PACKAGE_PIN R7 [get_ports SW[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[2]]
set_property PACKAGE_PIN R6 [get_ports SW[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[3]]
set_property PACKAGE_PIN R5 [get_ports SW[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[4]]
set_property PACKAGE_PIN V7 [get_ports SW[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[5]]
set_property PACKAGE_PIN V6 [get_ports SW[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[6]]
set_property PACKAGE_PIN V5 [get_ports SW[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[7]]
set_property PACKAGE_PIN U4 [get_ports SW[8]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[8]]
set_property PACKAGE_PIN V2 [get_ports SW[9]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[9]]
set_property PACKAGE_PIN U2 [get_ports SW[10]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[10]]
set_property PACKAGE_PIN T3 [get_ports SW[11]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[11]]
set_property PACKAGE_PIN T1 [get_ports SW[12]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[12]]
set_property PACKAGE_PIN R3 [get_ports SW[13]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[13]]
set_property PACKAGE_PIN P3 [get_ports SW[14]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[14]]
set_property PACKAGE_PIN P4 [get_ports SW[15]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[15]]

set_property PACKAGE_PIN L3 [get_ports SEG[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[0]]
set_property PACKAGE_PIN N1 [get_ports SEG[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[1]]
set_property PACKAGE_PIN L5 [get_ports SEG[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[2]]
set_property PACKAGE_PIN L4 [get_ports SEG[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[3]]
set_property PACKAGE_PIN K3 [get_ports SEG[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[4]]
set_property PACKAGE_PIN M2 [get_ports SEG[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[5]]
set_property PACKAGE_PIN L6 [get_ports SEG[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[6]]
set_property PACKAGE_PIN M4 [get_ports SEG[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SEG[7]]

set_property PACKAGE_PIN M1 [get_ports AN[7]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[7]]
set_property PACKAGE_PIN L1 [get_ports AN[6]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[6]]
set_property PACKAGE_PIN N4 [get_ports AN[5]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[5]]
set_property PACKAGE_PIN N2 [get_ports AN[4]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[4]]
set_property PACKAGE_PIN N5 [get_ports AN[3]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]
set_property PACKAGE_PIN M3 [get_ports AN[2]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
set_property PACKAGE_PIN M6 [get_ports AN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
set_property PACKAGE_PIN N6 [get_ports AN[0]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]