# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/shudian2/LAB_6/LAB_6.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/shudian2/LAB_6/LAB_6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/shudian2/lab6.v
read_xdc C:/Users/Administrator/Desktop/shudian2/lab6ys.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/shudian2/lab6ys.xdc]

synth_design -top lab6 -part xc7a100tcsg324-1
write_checkpoint -noxdef lab6.dcp
catch { report_utilization -file lab6_utilization_synth.rpt -pb lab6_utilization_synth.pb }
